site_name: Saaketh Ramoju Engineering
site_url: https://saakethramoju.github.io

theme:
  name: material
  icon:
    logo: material/rocket-launch
  palette:
    scheme: slate
  features:
    - navigation.top
    - navigation.path
    - content.code.copy

extra_css:
  - stylesheets/y2k-nasa.css
  - stylesheets/fullflow.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros

nav:
  - Home: index.md

  - Softwares:
      - Overview: softwares/index.md

      - ThermoProp: softwares/thermoprop/index.md

      - FullFlow:
          - Overview: softwares/fullflow/index.md
          - Introduction: softwares/fullflow/introduction.md
          - Installation: softwares/fullflow/installation.md
          - Introductory Example: softwares/fullflow/introductory-example.md
          - Steady-State Examples: softwares/fullflow/steady-state-examples.md
          - Transient Examples: softwares/fullflow/transient-examples.md
          - States: softwares/fullflow/states.md
          - Components:
              - Overview: softwares/fullflow/components/index.md
              - Custom Components: softwares/fullflow/components/custom-components.md
              - Nodes:
                  - Overview: softwares/fullflow/components/nodes/index.md
                  - Boundary: softwares/fullflow/components/nodes/boundary.md
          - Networks: softwares/fullflow/networks.md
          - Balances: softwares/fullflow/balances.md

      - Nozzle Contour Generator: softwares/nozzle-contour-generator/index.md

  - Notes:
      - Overview: notes/index.md

  - Projects:
      - Overview: projects/index.md