site_name: Saaketh Ramoju Engineering
site_url: https://saakethramoju.github.io

theme:
  name: material
  icon:
    logo: material/rocket-launch
  palette:
    scheme: slate
  features:
    - navigation.top
    - navigation.path
    - content.code.copy

extra_css:
  - stylesheets/y2k-nasa.css
  - stylesheets/fullflow.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros

nav:
  - Home: index.md

  - Softwares:
      - Overview: softwares/index.md

      - ThermoProp: softwares/thermoprop/index.md

      - FullFlow:
          - Overview: softwares/fullflow/index.md
          - Introduction: softwares/fullflow/introduction.md
          - Installation: softwares/fullflow/installation.md
          - Introductory Example: softwares/fullflow/introductory-example.md
          - Steady-State Examples: softwares/fullflow/steady-state-examples.md
          - Transient Examples: softwares/fullflow/transient-examples.md
          - States: softwares/fullflow/states.md
          - Components:
              - Overview: softwares/fullflow/components/index.md
              - Custom Components: softwares/fullflow/components/custom-components.md
              - Nodes:
                  - Overview: softwares/fullflow/components/nodes/index.md
                  - Boundaries:
                      - Boundary: softwares/fullflow/components/nodes/boundaries/boundary.md
                      - Pressure Boundary: softwares/fullflow/components/nodes/boundaries/pressure-boundary.md
                      - Temperature Boundary: softwares/fullflow/components/nodes/boundaries/temperature-boundary.md
                  - Volumes:
                      - Simple Volume: softwares/fullflow/components/nodes/volumes/simple-volume.md
                      - Volume: softwares/fullflow/components/nodes/volumes/volume.md
                  - Solids:
                      - Solid: softwares/fullflow/components/nodes/solids/solid.md
                  - Tanks:
                      - Simple Tank: softwares/fullflow/components/nodes/tanks/simple-tank.md
                      - Pressurized Tank: softwares/fullflow/components/nodes/tanks/pressurized-tank.md
                  - Combustion Chambers:
                      - Main Combustion Chamber: softwares/fullflow/components/nodes/combustion-chambers/main-combustion-chamber.md
                  - Junctions:
                      - Flow Splitter: softwares/fullflow/components/nodes/junctions/flow-splitter.md
                      - Flow Mixer: softwares/fullflow/components/nodes/junctions/flow-mixer.md
              - Branches:
                  - Discharge Coefficient:
                      - Discharge Coefficient: softwares/fullflow/components/branches/discharge-coefficient/discharge-coefficient.md
                      - Series CdA: softwares/fullflow/components/branches/discharge-coefficient/series-cda.md
                      - Parallel CdA: softwares/fullflow/components/branches/discharge-coefficient/parallel-cda.md
                      - Cavitating Venturi: softwares/fullflow/components/branches/discharge-coefficient/cavitating-venturi.md
                  - Compressible Flow:
                      - Isentropic Compressible Orifice: softwares/fullflow/components/branches/compressible-flow/isentropic-compressible-orifice.md
                      - Isentropic Area Change: softwares/fullflow/components/branches/compressible-flow/isentropic-area-change.md
                      - Compressible Flow Tube: softwares/fullflow/components/branches/compressible-flow/compressible-flow-tube.md
                      - Choked Fanno Flow: softwares/fullflow/components/branches/compressible-flow/choked-fanno-flow.md
                      - Choked Rayleigh Flow: softwares/fullflow/components/branches/compressible-flow/choked-rayleigh-flow.md
                      - Stationary Normal Shock: softwares/fullflow/components/branches/compressible-flow/stationary-normal-shock.md
                  - Convection Coefficients:
                      - Gnielinski: softwares/fullflow/components/branches/convection-coefficients/gnielinski.md
                      - Miropolskii: softwares/fullflow/components/branches/convection-coefficients/miropolskii.md
                      - Petukhov: softwares/fullflow/components/branches/convection-coefficients/petukhov.md
                      - Dittus-Boelter: softwares/fullflow/components/branches/convection-coefficients/dittus-boelter.md
                      - Sieder-Tate: softwares/fullflow/components/branches/convection-coefficients/sieder-tate.md
                      - Bartz: softwares/fullflow/components/branches/convection-coefficients/bartz.md
                      - Natural Convection: softwares/fullflow/components/branches/convection-coefficients/natural-convection.md
                      - Churchill-Chu: softwares/fullflow/components/branches/convection-coefficients/churchill-chu.md
          - Networks: softwares/fullflow/networks.md
          - Balances: softwares/fullflow/balances.md
          - Compositions: softwares/fullflow/compositions.md

      - Nozzle Contour Generator: softwares/nozzle-contour-generator/index.md

  - Notes:
      - Overview: notes/index.md

  - Projects:
      - Overview: projects/index.md