site_name: Saaketh Ramoju Engineering
site_url: https://saakethramoju.github.io

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.sections
    - navigation.top
    - navigation.path
    - content.code.copy

extra_css:
  - stylesheets/y2k-nasa.css

nav:
  - Home: index.md
  - Softwares:
      - Overview: softwares/index.md
      - ThermoProp: softwares/thermoprop/index.md
      - FullFlow: softwares/fullflow/index.md
      - Nozzle Contour Generator: softwares/nozzle-contour-generator/index.md
  - Engineering Notes:
      - Overview: engineering-notes/index.md
  - Projects:
      - Overview: projects/index.md